// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgOm-DZnBYUezGODXtX2jXXlLsuX7h0fQ',
    appId: '1:197761459040:web:740affa3b088287a017405',
    messagingSenderId: '197761459040',
    projectId: 'horse-bettings',
    authDomain: 'horse-bettings.firebaseapp.com',
    storageBucket: 'horse-bettings.appspot.com',
    measurementId: 'G-JVVL45GH5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMRjsJiK8pMA-9RGS1wgNSHwcjKKgOis',
    appId: '1:197761459040:android:1c570567e4782379017405',
    messagingSenderId: '197761459040',
    projectId: 'horse-bettings',
    storageBucket: 'horse-bettings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_LS4DggyyaZv4xfe5jf4vwgRwf2RQcg',
    appId: '1:197761459040:ios:07ca297ae89083bb017405',
    messagingSenderId: '197761459040',
    projectId: 'horse-bettings',
    storageBucket: 'horse-bettings.appspot.com',
    iosBundleId: 'com.example.horseBetting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_LS4DggyyaZv4xfe5jf4vwgRwf2RQcg',
    appId: '1:197761459040:ios:07ca297ae89083bb017405',
    messagingSenderId: '197761459040',
    projectId: 'horse-bettings',
    storageBucket: 'horse-bettings.appspot.com',
    iosBundleId: 'com.example.horseBetting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgOm-DZnBYUezGODXtX2jXXlLsuX7h0fQ',
    appId: '1:197761459040:web:c68b93cbf3272960017405',
    messagingSenderId: '197761459040',
    projectId: 'horse-bettings',
    authDomain: 'horse-bettings.firebaseapp.com',
    storageBucket: 'horse-bettings.appspot.com',
    measurementId: 'G-DM6MPE1SZ5',
  );
}
